In [1]:
import numpy as np
matriceV0 = []


# iAxisOfMatrix = 3
# jAxisOfMatrix = 3

def createMatrix(iAxisOfMatrix,jAxisOfMatrix):
    for i in range(iAxisOfMatrix):
        matriceV0.append([]) 
        for j in range(jAxisOfMatrix):
            matriceV0[i].append(0)
            


# createMatrix (iAxisOfMatrix,jAxisOfMatrix)

#matrice = np.array(matriceV0)




In [2]:
def printmatrix(matrice):
    print(matrice)

#printmatrix()

In [3]:
def switchPlayersTurn(player):
    if player == 'player1' :
        return 'player2'
    else:
        return 'player1'

#playersTurn = switchPlayersTurn('player2')

In [4]:
def modifyMatrix(ax_I,ax_J , playersTurn,matrice) :
    if playersTurn == 'player1' :
        matrice[ax_I][ax_J] = 1
    else:
        matrice[ax_I][ax_J] = 2
#modifyMatrix(0,2,playersTurn)
#matrice

In [5]:
# playersTurn = switchPlayersTurn('player1')
# modifyMatrix(1,1,playersTurn)
# printmatrix()
# print('****')
# modifyMatrix(1,2,playersTurn)
# printmatrix()
# print('****')
# modifyMatrix(2,2,playersTurn)
# printmatrix()


In [6]:
# def testInvalidPositionInMatrix(ax_I,ax_J,iAxisOfMatrix,jAxisOfMatrix,matrice):
#     if ( ax_I > iAxisOfMatrix  or  ax_J > jAxisOfMatrix or ax_I < 0 or ax_J < 0 ) :
#         print('this Position is out of bounds ')
#     elif matrice[ax_I][ax_J] !=0 :
#         print('this Position is take it by the other player ')


        


In [7]:


# Updated function that returns True or False
def testInvalidPositionInMatrix(ax_I, ax_J, iAxisOfMatrix, jAxisOfMatrix, matrice):
    if ax_I > iAxisOfMatrix or ax_J > jAxisOfMatrix or ax_I < 0 or ax_J < 0:
        return True  # Invalid position (out of bounds)
    elif matrice[ax_I][ax_J] != 0:
        return True  # Invalid position (already taken)
    else:
        return False  # Valid position


In [8]:
# def testIfIndex(matrice, ax_I , ax_J):
#     # pour( ax_I = 0 , ax_J = 0)

#      return (matrice[ax_I][ax_J] == matrice[ax_I][ax_J+1]  == matrice[ax_I][ax_J+2]  !=0  or  matrice[ax_I][ax_J] == matrice[ax_I+1][ax_J] == matrice[ax_I+1][ax_J]  !=0  or  matrice[ax_I][ax_J] == matrice[ax_I+1][ax_J+1] == matrice[ax_I+2][ax_J+2]  )
# # testIfIndex(matrice, 0 , 0)

In [9]:
#testInvalidPositionInMatrix(-5,5)

In [10]:


def checkTopLeftCorner(matrice, ax_I , ax_J):
    # pour( ax_I = 0 , ax_J = 0)
     return (matrice[ax_I][ax_J] == matrice[ax_I][ax_J+1]  == matrice[ax_I][ax_J+2]  !=0  or  matrice[ax_I][ax_J] == matrice[ax_I+1][ax_J] == matrice[ax_I+1][ax_J]  !=0  or  matrice[ax_I][ax_J] == matrice[ax_I+1][ax_J+1] == matrice[ax_I+2][ax_J+2]  !=0)
        
def checkBottomRightCorner(matrice, ax_I , ax_J):
   #pour(-1,-1)
    return (matrice[ax_I][ax_J] == matrice[ax_I][ax_J-1] == matrice[ax_I][ax_J-2]  !=0  or matrice[ax_I][ax_J] == matrice[ax_I-1][ax_J] == matrice[ax_I-1][ax_J]  !=0  or matrice[ax_I][ax_J] == matrice[ax_I-1][ax_J-1] == matrice[ax_I-2][ax_J-2]  !=0)  
    
def checkTopRightCorner(matrice, ax_I , ax_J):
    #pour(0,-1)
    return (matrice[ax_I][ax_J] == matrice[ax_I-1][ax_J] == matrice[ax_I-2][ax_J]  !=0  or matrice[ax_I][ax_J] == matrice[ax_I][ax_J+1] == matrice[ax_I][ax_J+2]  !=0  or matrice[ax_I][ax_J] == matrice[ax_I-1][ax_J-1] == matrice[ax_I-2][ax_J-2]  !=0  ) 
def checkBottomLeftCorner(matrice, ax_I , ax_J):
    #pour(-1,0)
    return (matrice[ax_I][ax_J] == matrice[ax_I+1][ax_J] == matrice[ax_I+2][ax_J]  !=0  or matrice[ax_I][ax_J] == matrice[ax_I][ax_J-1] == matrice[ax_I][ax_J-2]  !=0  or matrice[ax_I][ax_J] == matrice[ax_I-1][ax_J-1] == matrice[ax_I-2][ax_J-2]  !=0 ) 

    
def checkCenter(matrice, ax_I , ax_J):
    #pour centre
    return (matrice[ax_I][ax_J] == matrice[ax_I-1][ax_J] == matrice[ax_I+1][ax_J]  !=0  or matrice[ax_I][ax_J] == matrice[ax_I][ax_J-1] == matrice[ax_I][ax_J-1]  !=0  or matrice[ax_I][ax_J] == matrice[ax_I-1][ax_J-1] == matrice[ax_I-2][ax_J-2]  !=0    
            or matrice[ax_I][ax_J] == matrice[ax_I+1][ax_J+1] == matrice[ax_I-1][ax_J-1]  !=0  or matrice[ax_I][ax_J] == matrice[ax_I-1][ax_J-1] == matrice[ax_I+1][ax_J+1]  !=0  )


def checkTopLine(matrice, ax_I , ax_J):
    #i >0 and i< -1 and j =0
    return (matrice[ax_I][ax_J] == matrice[ax_I][ax_J+1] == matrice[ax_I][ax_J+2]  !=0  or matrice[ax_I][ax_J] == matrice[ax_I-1][ax_J] == matrice[ax_I+1][ax_J]  !=0 ) 
def checkBottomLine(matrice, ax_I , ax_J):
    #i >0 and i< -1 and j = -1
    return (matrice[ax_I][ax_J] == matrice[ax_I][ax_J-1] == matrice[ax_I][ax_J-2]  !=0  or matrice[ax_I][ax_J] == matrice[ax_I-1][ax_J] == matrice[ax_I+1][ax_J]  !=0 ) 
def checkRighLine(matrice, ax_I , ax_J):
    # j>0 and j< -1 and i = 0
    return (matrice[ax_I][ax_J] == matrice[ax_I+1][ax_J] == matrice[ax_I+2][ax_J]  !=0  or matrice[ax_I][ax_J] == matrice[ax_I][ax_J-1] == matrice[ax_I][ax_J+1]  !=0 ) 
def checkLeftLine(matrice, ax_I , ax_J):
    # j>0 and j< -1 and i = -1
    return (matrice[ax_I][ax_J] == matrice[ax_I-1][ax_J] == matrice[ax_I-2][ax_J]  !=0  or matrice[ax_I][ax_J] == matrice[ax_I][ax_J-1] == matrice[ax_I][ax_J+1]  !=0 ) 

def checkFordraw(matrice):
    if 0 not in matrice:
        return False  # Stop 
    return True  # Continue 


In [11]:
def checkWinPlayer(matrice, ax_I, ax_J):
    if ax_I == 0 and ax_J == 0 and checkTopRightCorner(matrice, ax_I, ax_J):
        print('player win')
    elif ax_I == -1 and ax_J == -1 and checkBottomRightCorner(matrice, ax_I, ax_J):
        print('player win')
    elif ax_I == 0 and ax_J == -1 and checkTopRightCorner(matrice, ax_I, ax_J):
        print('player win')
    elif ax_I == -1 and ax_J == 0 and checkBottomRightCorner(matrice, ax_I, ax_J):
        print('player win')
    elif ax_I > 0 and ax_J > 0 and checkBottomLeftCorner(matrice, ax_I, ax_J):
        print('player win')
    elif ax_I > 0 and ax_I < -1 and ax_J == 0 and checkTopLine(matrice, ax_I, ax_J):
        print('player win')
    elif ax_I > 0 and ax_I < -1 and ax_J == -1 and checkBottomLine(matrice, ax_I, ax_J):
        print('player win')
    elif ax_J > 0 and ax_J < -1 and ax_I == 0 and checkLeftLine(matrice, ax_I, ax_J):
        print('player win')
    elif ax_J > 0 and ax_J < -1 and ax_I == -1 and checkLeftLine(matrice, ax_I, ax_J):
        print('player win')



In [12]:

# iAxisOfMatrix = 3
# jAxisOfMatrix = 3
# createMatrix (iAxisOfMatrix,jAxisOfMatrix)
# matrice = np.array(matriceV0)
# printmatrix()
# print('*' * 50)
# ax_I=0
# ax_J=2
# playersTurn = 'player1'
# print(playersTurn)
# testInvalidPositionInMatrix(ax_I,ax_J)
# modifyMatrix(ax_I,ax_J,playersTurn)
# checkWinPlayer(matrice,ax_I,ax_J)
# printmatrix()
# print('*' * 50)
# playersTurn = switchPlayersTurn(playersTurn)
# print(playersTurn)
# ax_I=1
# ax_J=1
# testInvalidPositionInMatrix(ax_I,ax_J)
# modifyMatrix(ax_I,ax_J,playersTurn)
# checkWinPlayer(matrice,ax_I,ax_J)
# printmatrix()
# print('*' * 50)
# playersTurn = switchPlayersTurn(playersTurn)
# print(playersTurn)
# ax_I=0
# ax_J=1
# testInvalidPositionInMatrix(ax_I,ax_J)
# modifyMatrix(ax_I,ax_J,playersTurn)
# checkWinPlayer(matrice,ax_I,ax_J)
# printmatrix()
# print('*' * 50)
# playersTurn = switchPlayersTurn(playersTurn)
# print(playersTurn)
# ax_I=1
# ax_J=2
# testInvalidPositionInMatrix(ax_I,ax_J)
# modifyMatrix(ax_I,ax_J,playersTurn)
# checkWinPlayer(matrice,ax_I,ax_J)
# printmatrix()
# print('*' * 50)
# playersTurn = switchPlayersTurn(playersTurn)
# print(playersTurn)
# ax_I=0
# ax_J=0
# testInvalidPositionInMatrix(ax_I,ax_J)
# modifyMatrix(ax_I,ax_J,playersTurn)
# checkWinPlayer(matrice,ax_I,ax_J)
# printmatrix()


In [13]:

iAxisOfMatrix = int(input('iAxisOfMatrix'))
jAxisOfMatrix = int(input('jAxisOfMatrix'))
matrice = np.array(matriceV0)
createMatrix (iAxisOfMatrix,jAxisOfMatrix)
matrice = np.array(matriceV0)
printmatrix(matrice)
print('*' * 50)
playersTurn = 'player'+input('1 or 2')
playersTurn

while True:
    print(playersTurn, 'is your  turn')
    ax_I = int(input('Enter the row '))
    ax_J = int(input('Enter the column' ))

    testInvalidPositionInMatrix(ax_I, ax_J, iAxisOfMatrix, jAxisOfMatrix, matrice)
    modifyMatrix(ax_I, ax_J, playersTurn, matrice)
    
    if checkWinPlayer(matrice, ax_I, ax_J):
        break
    
    printmatrix(matrice)
    print('*' * 50)
    playersTurn = switchPlayersTurn(playersTurn)
    
    if not checkFordraw(matrice):
        break


[[0 0 0]
 [0 0 0]
 [0 0 0]]
**************************************************
player1 is your  turn
[[0 0 0]
 [0 0 1]
 [0 0 0]]
**************************************************
player2 is your  turn


IndexError: index 3 is out of bounds for axis 0 with size 3